version: '3'

services:
  todo-list:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: anbiasenggagau/todo-list
    environment:
      NODE_ENV: development
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DBNAME: todo4
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3306
    ports:
      - 3030:3030
    volumes:
      - ./index.js:/app/index.js
      - ./package.json/:/app/package.json
      - ./model/:/app/model
      - ./Controller/:/app/Controller
      - ./config/:/app/config
    command: npm run dev

# docker-compose -f docker-compose.debug.yml up -d --build
# docker-compose -f docker-compose.debug.yml down -v
